version: 0.5.0.0
run-mode: replace
source-paths:
  - src
excluded-paths: []
exclude-ignored-paths: true
template-paths:
  - headroom-templates
license-headers:
    haskell:
        put-after: ["^{-#"]
        put-before: ["^module"]
        margin-top-code: 1
        block-comment:
            starts-with: ^{- \|
            ends-with: (?<!#)-}$
variables:
    author: "Frederick Pringle"
    email: "frederick.pringle@fpringle.com"
